### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [algolia/laravel-scout-settings#12]
Can you make the latest commit an available release?

**Comment by julienbourdeau** [comment]
Yeah! I'll release this within the next 24 hours. I meant to do it for a few days!
Thanks for reminding me. 👌

**Comment by julienbourdeau** [comment]
We're currently working on adding a [nice way to export synonyms](https://github.com/algolia/algoliasearch-client-php/pull/326) in the php client. I'll wait until it's released to rely on this method.
I think it's worth it but I'm really sorry for the delay.

**Comment by julienbourdeau** [comment]
@ChrisThompsonTLDR I opened a new PR where I refactored synonyms with the new iterators. I also added support for query rules. Feel free to comment on it: https://github.com/algolia/laravel-scout-settings/pull/13

After it's merged, I'll make a new release.

**Comment by ChrisThompsonTLDR** [comment]
Closing this issue.  I think release 1.0.0 is rockin!  Working on getting it implemented in our stuff now.
