### ISSUE TITLE
forwardToReplicas cannot be set

### ISSUE THREAD

**Issue by HiradRoshandel** [algolia/laravel-scout-settings#17]
I cannot set `"forwardToReplicas":true` in my json settings and there is no way to set it from the dashboard. Is there a way to achieve this?

**Comment by julienbourdeau** [comment]
Currently, everything should be forwarded to replicas but it's not possible to override it. I assume yours aren't. I'll take a look today 👍

**Comment by HiradRoshandel** [comment]
Thanks @julienbourdeau. Currently, my replicas don't inherit/get updated when I change settings in the master

**Comment by julienbourdeau** [comment]
So I had a look, the way it works is that it will export settings for each index and replicas. For example index `names` and `names_replica` will have their own `resources/algolia-settings/names.json` and `resources/algolia-settings/names_replica.json` containing the entire settings list.
The philosophy of this extension is really to export everything to be able to add them to your git.

If you change the settings in the `resources/algolia-settings/names.json` file, it won't affect the replica, you need to update the other file too.

Could you detail the behavior you would expect?

**Comment by nunomaduro** [comment]
Thank you for creating this issue.

Unfortunately this repository will not receive any more updates. We should use now [Scout Extended](https://github.com/algolia/scout-extended).
