### ISSUE TITLE
Not supporting scout 4.0

### ISSUE THREAD

**Issue by jasonfish568** [algolia/laravel-scout-settings#18]
It seems algolia's packages aren't fully updated regarding laravel/scout 4.0

**Comment by aconital** [comment]
Use the master branch of Scout. Some functions like shouldBeSearchable() are not in the released version of scout yet

**Comment by adiachenko** [comment]
@aconital What are you talking about? There have been no changes to [shouldBeSearchable](https://github.com/laravel/scout/blob/4.0/src/Searchable.php#L91) method in 4.0. As far as I am aware, Taylor merged 3.0 into master and then tagged the latter as 4.0.

The latest release has some important changes to how index updates [work behind the scenes](https://github.com/laravel/scout/pull/252) which important for our projects. 

@julienbourdeau, can we please have your input on whether the 4.0 has any breaking changes or we can simply bump the version ion `composer.json`? Thanks.

**Comment by qrazi** [comment]
https://github.com/laravel/scout/compare/3.0...4.0

So I would think it is breaking changes, most notably the bump in PHP version required, but also switch to `searchable` to `shouldBeSearchable`.

**Comment by adiachenko** [comment]
@qrazi I apologize, I haven't been clear on my previous comment. 

`shouldBeSearchable` is but a syntactic sugar over existing functionality that seem to be outside the scope of this package anyway.

I do agree about php version bump though, but that is what semantic versioning is for and can simply be denoted by bumping the major version number (ie: 2.0).

My question was more in the line of whether there were breaking changes that actually break something  for the package as there is already a PR (#19) open in order to support newest Scout.

**Comment by qrazi** [comment]
@adiachenko No need for apologies, I didn't mean to come across as if that was needed. I was trying to add constructive information to this issue... 😅

Basically, agree with the major version bump, and did not see BC impact on this package besides the PHP version change.

**Comment by adiachenko** [comment]
Hey, guys. I decided to to do the fork temporarily as there are several pending fixes to the package that seem to take forever to get merged into mainline branch, namely incorrect handling of index prefixes (#15) and this very issue with new Scout release (#19).

You may use the following instructions to quickly avail of the latest fixes to the package, though I **recommend to create your own fork** if you intend to use it in production.

Add the following lines to your `composer.json`

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/adiachenko/laravel-scout-settings"
        }
    ],
    "require": {
        "algolia/laravel-scout-settings": "dev-fixed",
        "laravel/scout": "^4.0",
```

Then run `composer update algolia/laravel-scout-settings laravel/scout`.

P.S. I will support this fork until the aforementioned issues are fixed as they are blockers for the project I am currently working on.

**Comment by rikiless** [comment]
[1.0.1](https://github.com/algolia/laravel-scout-settings/releases/tag/1.0.1) with support of Laravel  Scout 4.0 is released.
