### ISSUE TITLE
Prefix use case

### ISSUE THREAD

**Issue by qrazi** [algolia/laravel-scout-settings#23]
With version 2.0.0 this package now has the capability to save the settings-files without the prefix defined by the env value `SCOUT_PREFIX` and used in Laravel with `config('scout.prefix')`.

This change was, I think, initiated by my earlier issue #14 . It is however still not enough to support my use case. This mostly relates to how replicas and primaries are defined in the settings.

Example background:
- Table is called "posts"
- Scout prefix is "test_"
- Two indices; primary "test_posts" and replica "test_posts_newest"

When the backup command is run, without prefix, files named "posts.json" and "posts_newest.json" will be created. Which is great, since their not tied to a specific environment. But the JSON in those files have properties that are environment specific, like `"replicas": ["test_posts_newest"]` and `"primary": "test_posts"`.

I am embarrassed that this slipped my attention when checking my PR and making the testcases. I am creating this issue mostly to:
- Check again my use case is valid
- Discuss the direction of implementation of a PR (which I would be happy to make)

My suggestion would be:
- On backup manipulate settings to remove the prefix from both the primary and replicas, similar to how it is removed from the filenames.
- On push manipulate settings to add back the prefix. This is actually a bit tricky to do in a fail-proof manner, since the `searchableAs()` methodology of Scout offers a lot of freedom in naming an index. Perhaps the indexname as know to Algolia should be kept on the repository too, just like the `usePrefix`-setting.

**Comment by julienbourdeau** [comment]
I agree the replicas should follow this `--prefix` option, we totally missed it. I opened a PR #24, feel free to review and share your thought on it.

**Comment by qrazi** [comment]
@julienbourdeau If you take a look at a branch I was working on to correct and expand the testsuite for this package, https://github.com/qrazi/laravel-scout-settings/tree/feat/more-tests, mostly since my initial tests ignored the actual name an index would have in a prefixed setup: https://github.com/qrazi/laravel-scout-settings/blob/feat/more-tests/tests/Algolia/Settings/Console/PushCommandTest.php#L33

Now, even if the replicas are including a prefix, the tests in this branch prove that the backup and push commands in `2.0.0` correctly remove the prefix from index names when it comes to creating the path to the settings files. 

What I meant with opening this request is the actual content of those settings files, for example:

```json
{
    "searchableAttributes": [
        "title"
    ],
    "replicas": [
        "testing_posts_newest",
        "testing_posts_oldest"
    ],
    "customRanking": null
}
```

is referring to the replicas `testing_posts_newest` and `testing_posts_oldest`. My assumption was that if these settings would committed, and used in a different environment, so with a different prefix (e.g. `prod_`), the settings that would be pushed to the production primary index (`prod_posts`) could then update that index to have the two testing replicas (since those are in the settings file, the content of which is send to the API).

Now I am kind of backtracking though, after reading the Algolia API docs and the `algolia/algolia-searchclient-php`. The `Index::setSettings()` method in its docblock does not mention that replicas can be set through this API call. On the other hand, the API docs, https://www.algolia.com/doc/rest-api/search/?language=php#get-index-settings, are referring to the Settings Parameter page, which does describe the replica property. 

**Attempt at scenario**:
Given the environment is setup with the Scout prefix `prod_`
And the settings file is called `posts.json`
And it contains JSON content
And the JSON has an array `replicas` of one item
And the value of that item is `testing_posts_newest`
When the settings are pushed
Then the primary index `prod_posts` should not have a replica with the name `testing_posts_newest`
And the primary index `prod_posts` should have a replica with the name `prod_posts_newest`

I hope this scenario explains the issue I thought I missed with the 2.0.0 release. 
Now, I haven't completely tested the actual behavior of the Algolia API when it comes to this, and I might have jumped the gun with my assumption that it would be needed to manipulate the actual content of the JSON files when it comes to the values of the `replicas` and `primary`.

**Comment by tobz-nz** [comment]
Whats the state of this PR? Sorry - am having this exact issue with replicas at the moment.
I can put in a little time to review/test if that helps :)

**Comment by nunomaduro** [comment]
Thank you for creating this issue.

Unfortunately this repository will not receive any more updates. We should use now [Scout Extended](https://github.com/algolia/scout-extended).
