### ISSUE TITLE
Not supporting Scout v5.0.1

### ISSUE THREAD

**Issue by ahren-condos-ca** [algolia/laravel-scout-settings#28]
It seems this package is not supporting Laravel/Scout 5.0.+. I'd appreciate it if anyone can help me with this.

**Comment by julienbourdeau** [comment]
Thanks for opening the issue. I have just release [`v2.0.1`](https://github.com/algolia/laravel-scout-settings/releases/tag/2.0.1) to fix this issue. Please let me know if it worked for you 👍

**Comment by HiradRoshandel** [comment]
It worked thanks @julienbourdeau
