### ISSUE TITLE
Incorrect examples in Algolia.com documentation

### ISSUE THREAD

**Issue by nullthoughts** [algolia/laravel-scout-settings#31]
### Description
The documentation on Algolia.com for [laravel-scout-settings](https://github.com/algolia/laravel-scout-settings) contains incorrect examples that will fail, originally corrected in PR https://github.com/algolia/laravel-scout-settings/pull/7

### Steps To Reproduce
Visit https://www.algolia.com/doc/api-client/laravel/managing-settings/?language=laravel#how-to-use

Without the use of quotes around the classname, the console command is striping characters from `$this->argument('model')` (App\ClassName becomes AppClassName).

### Possible Fixes
- As per @ChrisThompsonTLDR, update documentation to include quotes around the class name: `"App\ClassName"`
- Or change documentation to escape backslash in command: `App\\ClassName`

**Comment by nunomaduro** [comment]
Thank you for creating this issue.

Unfortunately this repository will not receive any more updates. We should use now [Scout Extended](https://github.com/algolia/scout-extended).
