### ISSUE TITLE
Support for Search Client PHP 2.*

### ISSUE THREAD

**Issue by Lotuashvili** [algolia/laravel-scout-settings#32]
I'm using [Scout Extended](https://github.com/algolia/scout-extended) package for Laravel, which requires `algoliasearch-client-php` version 2+. So can't install this package with extended scout.

![image](https://user-images.githubusercontent.com/6238393/51806292-bc85d300-2291-11e9-9021-951eea38702b.png)

Thanks in advance!

**Comment by nunomaduro** [comment]
Hey @Lotuashvili, Scout Extended have it's own way of handling settings.

You can remove the package `laravel-scout-settings` and use this: https://www.algolia.com/doc/framework-integration/laravel/indexing/configure-index.

**Comment by nunomaduro** [comment]
Thank you for creating this issue.

Unfortunately this repository will not receive any more updates. We should use now [Scout Extended](https://github.com/algolia/scout-extended).
